build: util_ScriptExecutor.h middleware.c
	gcc -fPIC -I /usr/lib/jvm/java-8-openjdk-amd64/include/ -I /usr/lib/jvm/java-8-openjdk-amd64/include/linux/ -o libmiddleware.so -shared middleware.c
clean:
	rm *.so
