/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class util_ScriptExecutor */

#ifndef _Included_util_ScriptExecutor
#define _Included_util_ScriptExecutor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     util_ScriptExecutor
 * Method:    execute
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_util_ScriptExecutor_execute
  (JNIEnv *, jobject, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
